- name: Install Apache Tomcat10 using ansible
  hosts: localhost
  connection: local
  remote_user: ubuntu
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      apt:
        name: default-jdk
        state: present


    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat10
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
		 - name: Copy Tomcat service from local to remote
      copy:
        src: /opt/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755
        remote_src: yes
    - name: Copy artifacts from local to remote
      copy:
        src: /opt/cargo-tracker-1.0-20220710.093159-1.war
        dest: /opt/tomcat10/webapps
        mode: 0755
        remote_src: yes
    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: restarted
        daemon_reload: true
